version: "3"
services:
    api:
        container_name: bountyboard
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
            - "8001:443"
        environment:
            - ASPNETCORE_HTTPS_PORT=8001
            - ASPNETCORE_Kestrel__Certificates__Default__Password=ufo
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dev_cert.pfx
            - ASPNETCORE_URLS=https://+;http://+
        volumes:
            - ./conf.d/https/:/https/